---

- name: Converge
  hosts: all
  # environment:
  #   http_proxy: "{{ lookup('env', 'http_proxy') }}"
  #   https_proxy: "{{ lookup('env', 'https_proxy') }}"
  #   no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  vars:
    harden_apache_phpremi_rhel_enable: true
  pre_tasks:
    - name: Ubuntu | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 16)
    - name: RedHat | Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (yum install -y python3)
      register: python3
      changed_when: "'installed' in python3.stdout"
      when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8)
    - name: Gather Facts
      ansible.builtin.setup:
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 16)
    - name: Ubuntu Bionic+, Redhat 8+ | Enforce python3 for ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: >
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int >= 16) or
        (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8)
    - name: Redhat 10+ | Disable mod_security
      ansible.builtin.set_fact:
        hardenwebserver_modsecurity_enable: false
      when: >
        (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 10)
  roles:
    - { role: juju4.redhat_epel, when: ansible_facts.os_family == "RedHat" and ansible_facts.distribution != "Fedora"}
    - juju4.harden_apache
