---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 4
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  enable_yum_epel: true
  # name: chef_solo
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: centos/8
  - name: centos/7

suites:
  - name: default
    run_list:
    attributes:
  - name: bind-restriction
    run_list:
    attributes:
      hardenwebserver_bind: 127.0.0.1
    includes:
      - ubuntu-18.04
      - centos/7
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default/default.yml
  - name: default-ad-sso
    run_list:
    attributes:
    includes:
      - ubuntu-18.04
      - centos/7
