---
driver:
  name: docker
## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false
## for systemd/centos7, https://github.com/docker/docker/issues/7459 = not enough
#  privileged: true
#  run_options: -e "container=docker" -v /sys/fs/cgroup:/sys/fs/cgroup

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
#  ansible_yum_repo: https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
#  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-18.04
    driver_config:
# https://github.com/test-kitchen/kitchen-docker/issues/285
      provision_command: mkdir -p /run/sshd
  - name: ubuntu-16.04
  - name: ubuntu-14.04
#  - name: ubuntu-12.04
  - name: centos-7
#  - name: centos-6
### Ansible 2.2+/cryptography: https://github.com/ansible/ansible/issues/276
#    provisioner:
#      ansible_version: 2.1.2.0
## tool chain kitchen and image need customization... nok currently
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
  - name: default-ad-sso
    run_list:
    attributes:
  - name: default-syslog
    run_list:
    attributes:
