---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  enable_yum_epel: true
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: centos-8
  - name: centos-7
    ## httpd/centos7/capability issue on lxc
    ## https://github.com/lxc/lxd/issues/1245	= only choice is privileged
    ## https://bugzilla.redhat.com/show_bug.cgi?id=1012952
    driver:
      config:
        security.privileged: true

suites:
  - name: default
    run_list:
    attributes:
  - name: default-vascan
    run_list:
    includes:
      - ubuntu-18.04
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default-vascan/default.yml
  - name: default-ad-sso
    run_list:
    attributes:
