---
driver:
  name: docker
  ## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_chef_omnibus: true
  require_ansible_omnibus: true
  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
    driver_config:
      # https://github.com/test-kitchen/kitchen-docker/issues/285
      provision_command: mkdir -p /run/sshd
  - name: centos-8
  - name: centos-7

suites:
  - name: default
    run_list:
    attributes:
  - name: default-ad-sso
    run_list:
    attributes:
  - name: default-syslog
    run_list:
    attributes:
