---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  enable_yum_epel: true
  require_ansible_omnibus: true
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-22.04
  - name: ubuntu-20.04
  - name: centos-9-Stream
  - name: centos-8-Stream
  - name: debian-bullseye

suites:
  - name: default
    run_list:
    attributes:
  - name: default-vascan
    run_list:
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default-vascan/default.yml
  - name: default-ad-sso
    run_list:
    attributes:
