---

- name: apache-security packages install
  package: name={{ hardenwebserver_packages }} state=present
  register: pkginstall
  until: pkginstall is success

- block:
    - name: RedHat7 | reload systemd
      systemd:
        daemon_reload: true
        name: httpd
      when: >
        ansible_distribution_version.split(".")[0] == '7' and
        pkginstall.changed and
        not (ansible_virtualization_type is defined and (ansible_virtualization_type == "docker"))
  when: ansible_os_family == "RedHat"

- include: apache-ssl.yml

- include: apache-security.yml

- include: apache-modsecurity.yml

- include: apache-https-only.yml
  when: hardenwebserver_disable_http is defined and hardenwebserver_disable_http|bool

- include: apache-bind-debian.yml
  when: >
    hardenwebserver_bind is defined and
    hardenwebserver_bind and
    (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
- include: apache-bind-redhat.yml
  when: >
    hardenwebserver_bind is defined and
    hardenwebserver_bind and
    ansible_os_family == "RedHat"

- include: php.yml
  when: harden_apache_php_enable is defined and harden_apache_php_enable|bool

- include: csp-report.yml
  when: harden_apache_cspreport_template is defined and harden_apache_cspreport_template

- include: apache-ad-sso.yml
  when: harden_apache_ad_sso|bool

- name: ensure apache is enabled and started
  service: name={{ apache_svc }} state=started enabled=yes
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
