---

- name: RedHat | Set fact
  ansible.builtin.set_fact:
    php_remi_version_short: "{{ harden_apache_phpremi_rhel_version | replace('.', '') }}"
    php_remi_version: "{{ harden_apache_phpremi_rhel_version }}"
    harden_apache_phpdir: /etc/php

- name: RedHat | Import Remi rpm repository keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - https://rpms.remirepo.net/RPM-GPG-KEY-remi2021
  register: pkg_result

- name: RedHat | Install Remi repo
  ansible.builtin.dnf:
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present
  when: "'remi-release' not in ansible_facts.packages"
  register: pkg_result
  until: pkg_result is success

- name: RedHat | Check if remi-php repo is enabled
  ansible.builtin.command: "grep '^enabled=' /etc/yum.repos.d/remi-php{{ php_remi_version_short }}.repo"
  register: remistate
  changed_when: false
  when: ansible_distribution_major_version | int < 8

# https://github.com/ansible/ansible-modules-extras/issues/2384
- name: RedHat | Enable remi repository for php
  ansible.builtin.command: "yum-config-manager --enable remi-php{{ php_remi_version_short }}"  # noqa no-changed-when
  # yum_repository:
  #   name: remi-php56
  #   enable: yes
  when:
    - ansible_distribution_major_version | int < 8
    - remistate.stdout is defined
    - not ('enabled=1' in remistate.stdout)

- name: RedHat | reset php stream to use remi latest
  ansible.builtin.command: "dnf module reset php -y"  # noqa no-changed-when
  when:
    - ansible_distribution_major_version | int >= 8
    - ansible_facts.packages['php-fpm'] is defined
    - ansible_facts.packages['php-fpm'][0]['version'] is version_compare(php_remi_version, '<')

- name: RedHat | enable remi repository for php
  ansible.builtin.command: "dnf module enable php:remi-{{ php_remi_version }} -y"  # noqa no-changed-when
  when: ansible_distribution_major_version | int >= 8

- name: RedHat | Ensure PHP Remi is present
  ansible.builtin.package:
    name:
      - php
      - php-devel
    state: present
  async: 3600
  poll: 300
  register: pkg_result
  until: pkg_result is success
