---
# http://www.rsyslog.com/recipe-apache-logs-rsyslog-parsing-elasticsearch/
# https://www.loggly.com/ultimate-guide/centralizing-apache-logs/
# * rsyslog existing apache log ingestion, with json or not
# * apache pipe to logger

- name: Ensure rsyslog is present
  package:
    name: rsyslog
    state: present
  register: pkg_result
  until: pkg_result is success

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/s1-working_with_queues_in_rsyslog#sec-Creating_a_New_Directory_for_rsyslog_Log_Files
- name: Ensure rsyslog work directory exists
  file:
    dest: "{{ rsyslog_workdirectory }}"
    state: directory
    mode: '0755'
    setype: syslogd_var_lib_t
  when: ansible_os_family == 'RedHat'

- name: Configure rsyslog to ingest apache logs
  template:
    src: "{{ harden_apache_rsyslog_template }}"
    dest: "/etc/rsyslog.d/apache2syslog"
    owner: root
    group: root
    mode: '0644'
    validate: 'rsyslogd -N2 -f %s'
  notify:
    - restart rsyslog
