---

- name: Ensure curl is present
  ansible.builtin.package:
    name: curl
    state: present

- name: Import testing-siege
  ansible.builtin.import_tasks: testing-siege.yml
  when: ansible_distribution_major_version|int < 8

- name: Import testing-h2load
  ansible.builtin.import_tasks: testing-h2load.yml
  when: harden_apache_testing_h2load
