---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -x 204,306,303
  flake8
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:20.04}
    groups:
      - hardenapache
    env:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 0
scenario:
  name: default
verifier:
  name: ansible
