---
name: AnsibleCI

on:
  push:
  pull_request:
  schedule:  # run weekly, every Tuesday 03:00
    - cron: '0 3 * * 2'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
      ANSIBLE_EXTRA_VARS: "-e harden_apache_testing_h2load=false"

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.harden_apache
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
          echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
          ansible --version
          cd $GITHUB_WORKSPACE/juju4.harden_apache
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          { echo '[defaults]'; echo 'callback_whitelist = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: yamllint
        run: |
          cd $GITHUB_WORKSPACE/juju4.harden_apache && yamllint .
      - name: ansible-lint
        run: |
          cd $GITHUB_WORKSPACE/juju4.harden_apache && ansible-lint
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/juju4.harden_apache && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/juju4.harden_apache && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: On failure
        run: |
          ansible -i inventory --connection=local -m setup localhost
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com
          ping -c 1 8.8.8.8
          ps axuw
          netstat -anp
          cc --version
          c++ --version
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - systemd
        run: |
          systemctl -l --no-pager status apache2 || true
          systemd-analyze security || true
          rsyslogd -v
          apachectl -v
          sudo apachectl -t
          sudo apachectl -l
        continue-on-error: true
      - name: After script - etc
        run: |
          sudo cat /etc/apache2/sites-available/000-default.conf
          sudo cat /etc/apache2/sites-available/default-ssl.conf
          sudo cat /etc/modsecurity/modsecurity.conf
        continue-on-error: true
      - name: After script - files
        run: |
          sudo find /etc/apache2 -type f -ls
        continue-on-error: true
      - name: After script - curl
        run: |
          curl -vk https://localhost
          curl -vk https://localhost?a=b
          curl -vk -X HEAD https://localhost
          curl -vk -X OPTIONS https://localhost
          curl -vk -H Referer:http://www.example.com -H X-Forwarded-For:127.0.0.128 https://localhost/
          curl -vk --cookie COOKIE=test_cookie https://localhost
          curl -vk -H "Referer: http://www.example.com" -H "X-Forwarded-For: 127.0.0.128" "https://localhost/?a=b&c=d"
        continue-on-error: true
      - name: After script - logs
        run: |
          ls -la /var/log/apache2
          sudo find /var/log/apache2 -type f -exec tail -50 {} \;
        continue-on-error: true
